### ISSUE TITLE
Task memberships

### ISSUE THREAD

**Issue by lucaskatayama** [Asana/java-asana#17]
Hi,

How can I put memberships information, using .data() method?

Thanks

**Comment by noonhub** [comment]
@lucaskatayama it looks like this is a bug in the API around string IDs in the memberships parameter that the client is hitting.

In general the memberships parameter should look like

    "memberships": [ { "project": 123, section: 456 } ]

The project and section objects should be referenced with just their IDs.

The bug is that the client converts all IDs to strings before sending them to the API. This is fine because the API _should_ accept string IDs. However, there appears to be a bug with this specific parameter causing a server error when string IDs are passed.

I am working to get this fixed in the API. In the mean time, a workaround would be to create the task and then set the project and section using the [`addProject()`](https://asana.com/developers/api-reference/tasks#projects) method instead.

**Comment by lucaskatayama** [comment]
Ahh OK Thanks
