### ISSUE TITLE
API Dependency to Spark ?

### ISSUE THREAD

**Issue by prismec** [Asana/java-asana#36]
I've just integrated the client libraries and noticed that there is a dependency on Spark and, transitively, dependencies to Jetty. I am wondering if this is really required when I just want to use the API ? I did a quick full text search and it seems that Spark is only used in the Examples.

I therefore guess that I can just exclude this dependency. And I'm wondering if that would not be the natural default for the client libraries ?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694757934856/182694767736605)

**Comment by marcogallotta** [comment]
Thanks for reporting! This looks like it slipped through and shouldn't be there. I'll make sure we follow-up and get it removed.

**Comment by McAndze** [comment]
It's not a problem for me personally, just thought I'd let you know that this is still the case in the latest version (0.5.0).

**Comment by praecipula** [comment]
Thanks for catching that :) 0.5.0 was actually written just before you posted to include support for custom fields; but it turns out that that version of the library never actually landed in Maven (oops, my fault), so 0.5.0 doesn't have any changes with regards to removing this dependency. Our next version will get this fixed though and (hopefully) get successfully pushed to Maven as well.

**Comment by joetrollo** [comment]
We have relocated the examples and removed this dependency in the latest release.
