### ISSUE TITLE
Batch support?

### ISSUE THREAD

**Issue by asufty888** [Asana/java-asana#75]
Are there any plans to incorporate Batch support?

**Comment by praecipula** [comment]
I expect that we'll get there eventually, but it's a longer-tail feature to pull into specifically java-asana. The reason is that the batch payload is very unlike every other payload in our API and doesn't have a model for it yet (com.asana.model.*) This means that in our Java client library we'd have to reimplement classes under https://github.com/Asana/java-asana/tree/master/src/main/java/com/asana/models to be a "batch" payload of heterogeneous items which then is dynamically deserialized on response into different heterogeneous items; and this is a new idiom in our client library so a fairly big chunk of work.

As a workaround, you can build your own Request (https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/requests/Request.java) and set its data to an appropriate payload (it's a Map of <String, Object> that is the JSON data represented in Java Map form) and pass it to `client.request` https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/Client.java#L180. If done correctly, you can deserialize into the JSON object (like here: https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/requests/CollectionRequest.java#L46). In the normal course of things, this JSON object gets mapped into a statically-typed model (check https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/resources/gen/TasksBase.java#L39 - the Task.class on that line is the task _model_ which maps out the JSON - but you can use the JSON directly if that's easier.

Sorry for the hassle of all this, but we hope you understand that this isn't a super trivial implementation in statically-typed languages. Fingers crossed we can allocate bandwidth to it at some point!
