### ISSUE TITLE
Attachment downloadUrl, viewUrl, host is null, but on Asana.com I can view the attachment

### ISSUE THREAD

**Issue by dusty1997** [Asana/java-asana#83]
Hi, 

    ItemRequest<Attachment> itemRequest = client.attachments.createOnTask(taskId, fileInputStream, "attachment.jpg", ".jpg");    

This is the line that creates the attachment on my task, it works. On Asana.com if i go to the task i can see that the attachment has been added, and when I click on it I can view the attachment.jpg.

However, when I go to download the attachment: 

     CollectionRequest<Attachment> itemRequest = client.attachments.findByTask(taskId);
            List<Attachment> list = itemRequest.execute();
            Log.w("ASANA_API","Get Attachment, listSize: " + list.size());
            if(list.size() >= 1){
                task = list.get(0);
                Log.w("get_attachment",task.downloadUrl + " :URL:" + task.viewUrl + ", host: " + task.host + ", " + task.name);
            } else {
                errorMessage = "No Attachments";
                return null;
            } .    

The Log.w returns "W/get_attachment: null :URL:null, host: null, attachment.jpg". Why is this, or is there a better way I can get the attachment from the task?

**Comment by rossgrambo** [comment]
Hello @dusty1997,

Those fields are empty because that endpoint returns the Compact form of the Attachment objects. ( See: https://asana.com/developers/api-reference/attachments#get-all-task vs https://asana.com/developers/api-reference/attachments#get-single ).

I would recommend fixing this by opting into those fields in your request ( See: https://asana.com/developers/documentation/getting-started/input-output-options ):
```
itemRequest.option("fields", Arrays.asList("download_url", "view_url", "host", "name"));
```

Or you could do an individual request after you have the attachment's Id:
```
task = list.get(0);
ItemRequest<Attachment> singleItemRequest = client.attachments.findById(task.id);
task = singleItemRequest.execute();
```

You might want also want to rename the variable 'task' to something more representative, like 'attachment'.

Cheers!
