### ISSUE TITLE
Get new Sync token exception

### ISSUE THREAD

**Issue by AntonyLeons** [Asana/java-asana#94]
An exception is always thrown when you attempt to get a new sync token, Is this the expected behaviour. If so how would you get a new sync token from the server, without an exception.

`com.asana.errors.InvalidTokenError: Sync token invalid or too old (Sync token invalid or too old. If you are attempting to keep resources in sync, you must fetch the full dataset for this query now and use the new sync token for the next sync.) at com.asana.errors.AsanaError.mapException`.

here is a short example

`  CollectionRequest events = client.events.get(project_id);
        Sync_Token = events.executeRaw().sync;
        events = client.events.get(project_id,Sync_Token);`

**Comment by rossgrambo** [comment]
See the [EventsPageIterator](https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/iterator/EventsPageIterator.java) &/or [EventsRequest](https://github.com/Asana/java-asana/blob/master/src/main/java/com/asana/requests/EventsRequest.java). It would probably be easier to use these instead of manually updating the sync token. But if you want to do it manually, see the code that these objects use.

You probably want to do something like:

```
        Iterator events = client.events.get(project_id).iterator();

        // Loop iterator
```
